# Generated by Django 3.2.5 on 2021-07-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bors_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='colour',
            field=models.CharField(default='brown', max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.CharField(default='Its a cute dog', max_length=500),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='bors_server.user'),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
